trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - docs/*

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  buildConfiguration: 'Release'

steps:

# Restore NuGet Packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Check for Vulnerable Packages
- script: dotnet list package --vulnerable
  displayName: 'Check for Vulnerable Packages'


# Build the Project
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'